version: '3.6'

services:
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: victr
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  backend:
    build: ./api
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/victr
    networks:
      - default
    ports:
      - "5000:5000"
    volumes:
        - ./api:/code
    restart: always
  
  frontend:
    build: ./app
    user: victr
    depends_on:
      - backend
    networks:
      - default
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./app:/opt/app
